### ISSUE TITLE
Option to choose/configure warning prior to shocks

### ISSUE THREAD

**Issue by redmushie** [OpenShock/WebUI#48]
It'd be nice to have a feature in the UI where you can choose a type and parameters for a warning signal prior to giving out shocks.

- Off/Vibrate/Beep
- Both fixed and random durations would be nice.
  - In case of fixed duration, a single slider.
  - In case of random duration, a minimum and maximum slider.

**Comment by LucHeart** [comment]
Implemented in 3.6.0
