### ISSUE TITLE
Add full semver support

### ISSUE THREAD

**Issue by hhvrc** [OpenShock/WebUI#69]
Would be nice to support 1.0.0-dev etc

**Comment by hhvrc** [comment]
Good library for this 😄 
https://www.npmjs.com/package/semver

**Comment by LucHeart** [comment]
rel. https://github.com/OpenShock/API/issues/29

**Comment by redmushie** [comment]
https://github.com/OpenShock/API/issues/29 is closed, does this need any work on this side @LucHeart ?

UI seems to handle it fine (to my knowledge) ![image](https://github.com/OpenShock/WebUI/assets/82113471/abdd9803-7d46-446d-9864-561eb371e9af)

**Comment by LucHeart** [comment]
yes otherwise it wouldnt work on the ui aswell
